name: Docker Image CI

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
      - name: Install
        run: bun i
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
      - name: Install
        run: bun i
      - name: Run test
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          sid: ${{ secrets.SID }}
        run: bun test --reporter=junit --reporter-outfile=./bun.xml 

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jonasfranke/nepapi:latest
            ghcr.io/jonasfranke/nepapi:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image (no master)
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jonasfranke/nepapi:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
